name: Build and Push Docker Image (Dev)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Dev Tag)
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t qingfeng2336/stream-vault:dev \
            --push \
            -f ./backstage/src/main/docker/buildx/Dockerfile.dev \
            ./backstage/src/main/docker/buildx
